[2025-09-23T04:46:12.570+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:46:12.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:46:12.589+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:46:12.587+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:46:12.605+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:46:12.601+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:46:12.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:46:12.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.109 seconds
[2025-09-23T04:46:43.210+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:46:43.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:46:43.213+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:46:43.212+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:46:43.230+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:46:43.224+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:46:43.231+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:46:43.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.118 seconds
[2025-09-23T04:47:13.498+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:47:13.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:47:13.502+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:47:13.502+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:47:13.513+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:47:13.511+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:47:13.514+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:47:13.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.053 seconds
[2025-09-23T04:47:43.617+0000] {processor.py:161} INFO - Started process (PID=203) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:47:43.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:47:43.625+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:47:43.623+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:47:43.667+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:47:43.659+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:47:43.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:47:43.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.112 seconds
[2025-09-23T04:48:13.771+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:48:13.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:48:13.780+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:48:13.780+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:48:13.798+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:48:13.795+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:48:13.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:48:13.897+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.139 seconds
[2025-09-23T04:48:43.964+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:48:43.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:48:43.969+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:48:43.969+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:48:43.981+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:48:43.977+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:48:43.982+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:48:44.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.052 seconds
[2025-09-23T04:49:14.089+0000] {processor.py:161} INFO - Started process (PID=363) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:49:14.091+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:49:14.093+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:49:14.093+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:49:14.125+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:49:14.117+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:49:14.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:49:14.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.147 seconds
[2025-09-23T04:49:44.293+0000] {processor.py:161} INFO - Started process (PID=377) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:49:44.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:49:44.297+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:49:44.296+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:49:44.305+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:49:44.303+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:49:44.306+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:49:44.339+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.053 seconds
[2025-09-23T04:50:14.424+0000] {processor.py:161} INFO - Started process (PID=387) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:50:14.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:50:14.427+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:50:14.427+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:50:14.437+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:50:14.435+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:50:14.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:50:14.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.050 seconds
[2025-09-23T04:50:44.531+0000] {processor.py:161} INFO - Started process (PID=397) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:50:44.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:50:44.535+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:50:44.535+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:50:44.543+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:50:44.541+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:50:44.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:50:44.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.041 seconds
[2025-09-23T04:51:14.639+0000] {processor.py:161} INFO - Started process (PID=407) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:51:14.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:51:14.642+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:51:14.642+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:51:14.650+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:51:14.648+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:51:14.651+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:51:14.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.044 seconds
[2025-09-23T04:51:44.765+0000] {processor.py:161} INFO - Started process (PID=417) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:51:44.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:51:44.768+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:51:44.768+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:51:44.776+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:51:44.774+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:51:44.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:51:44.803+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.045 seconds
[2025-09-23T04:52:14.880+0000] {processor.py:161} INFO - Started process (PID=427) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:52:14.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:52:14.883+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:52:14.882+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:52:14.890+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:52:14.889+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:52:14.891+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:52:14.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.040 seconds
[2025-09-23T04:52:44.963+0000] {processor.py:161} INFO - Started process (PID=437) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:52:44.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:52:44.966+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:52:44.966+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:52:44.974+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:52:44.972+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:52:44.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:52:44.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.041 seconds
[2025-09-23T04:53:15.056+0000] {processor.py:161} INFO - Started process (PID=447) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:53:15.057+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:53:15.058+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:53:15.058+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:53:15.065+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:53:15.063+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:53:15.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:53:15.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.037 seconds
[2025-09-23T04:53:45.139+0000] {processor.py:161} INFO - Started process (PID=457) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:53:45.140+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:53:45.142+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:53:45.141+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:53:45.149+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:53:45.148+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:53:45.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:53:45.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.038 seconds
[2025-09-23T04:54:15.225+0000] {processor.py:161} INFO - Started process (PID=467) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:54:15.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:54:15.227+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:54:15.227+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:54:15.235+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:54:15.233+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:54:15.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:54:15.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.042 seconds
[2025-09-23T04:54:45.321+0000] {processor.py:161} INFO - Started process (PID=800) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:54:45.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:54:45.324+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:54:45.324+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:54:45.338+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:54:45.332+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:54:45.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:54:45.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.057 seconds
[2025-09-23T04:55:15.426+0000] {processor.py:161} INFO - Started process (PID=810) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:55:15.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:55:15.428+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:55:15.428+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:55:15.436+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:55:15.434+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:55:15.436+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:55:15.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.037 seconds
[2025-09-23T04:55:45.513+0000] {processor.py:161} INFO - Started process (PID=820) to work on /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:55:45.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/2spark_iceberg_pipeline.py for tasks to queue
[2025-09-23T04:55:45.517+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:55:45.516+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:55:45.525+0000] {logging_mixin.py:188} INFO - [2025-09-23T04:55:45.523+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/2spark_iceberg_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/2spark_iceberg_pipeline.py", line 117, in <module>
    process_taxi_data = SparkSubmitOperator(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 139, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 882, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SparkSubmitOperator (task_id: process_taxi_data). Invalid arguments were:
**kwargs: {'master': 'spark://spark-master:7077'}
[2025-09-23T04:55:45.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/2spark_iceberg_pipeline.py
[2025-09-23T04:55:45.553+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/2spark_iceberg_pipeline.py took 0.049 seconds
